services:
  uwud:
    container_name: uwud
    image: uwud:latest
    build:
      context: .
    restart:  unless-stopped
    volumes:
      - ./config:/app/config
      - ./images:/app/static/images/custom
    ports:
      - 80:8080
