[general]
title="some title"
desc="some desc"
icon="https://cdn.7tv.app/emote/01F6NM2T080003C6R1CKK0T0P2/4x.avif"
columns=3

[[sections]]
name = ""
description = "Services for the first category."
icon = "https://cdn.7tv.app/emote/01G6WYS1RR0004RPYH3C4ANGVV/4x.avif"
[[sections.items]]
name="some service 1"
url="https://100.114.49.127"
desc="some desc 1"
health="https://100.114.49.127"
icon="https://cdn.7tv.app/emote/01F5VW2TKR0003RCV2Z6JBHCST/4x.avif"
[[sections.items]]
name="some service 2"
url="https://100.114.49.127"
desc="some desc 2"
health="https://100.114.49.127"
[[sections.items]]
name="some service 3"
url="https://100.114.49.127"
desc="some desc 3 this thing has no health check"

[[sections]]
name = "My First Section"
description = "Services for the first category."
[[sections.items]]
name="some service 1"
url="https://100.114.49.127"
desc="some desc 1"
health="https://100.114.49.127"
icon="https://cdn.7tv.app/emote/01F5VW2TKR0003RCV2Z6JBHCST/4x.avif"
[[sections.items]]
name="some service 2"
url="https://100.114.49.127"
desc="some desc 2"
health="https://100.114.49.127"
[[sections.items]]
name="some service 3"
url="https://100.114.49.127"
desc="some desc 3 this thing has no health check"

[[sections]]
name = "My First Section"
description = "Services for the first category."
icon = "https://cdn.7tv.app/emote/01F5VW2TKR0003RCV2Z6JBHCST/4x.avif"
[[sections.items]]
name="some service 1"
url="https://100.114.49.127"
desc="some desc 1"
health="https://100.114.49.127"
icon="https://cdn.7tv.app/emote/01F5VW2TKR0003RCV2Z6JBHCST/4x.avif"
[[sections.items]]
name="some service 2"
url="https://100.114.49.127"
desc="some desc 2"
health="https://100.114.49.127"
[[sections.items]]
name="some service 3"
url="https://100.114.49.127"
desc="some desc 3 this thing has no health check"

[[sections]]
name = "My First Section"
[[sections.items]]
name="some service 1"
url="https://100.114.49.127"
desc="some desc 1"
health="https://100.114.49.127"
icon="https://cdn.7tv.app/emote/01F5VW2TKR0003RCV2Z6JBHCST/4x.avif"
[[sections.items]]
name="some service 2"
url="https://100.114.49.127"
desc="some desc 2"
health="https://100.114.49.127"
[[sections.items]]
name="some service 3"
url="https://100.114.49.127"
desc="iajsfiajfiajfiajfij"
